

[build.environment]
  # Node.js version for Netlify
  NODE_VERSION = "18"

# Redirect rules for SPA (Single Page )
[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
