[build]
  # Build command for Vite + React + TypeScript
  command = "npm run build"
  # Publish directory (Vite's default output directory)
  publish = "dist"

[build.environment]
  # Node.js version for Netlify
  NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  # Apply these headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Performance headers
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache static assets (JS, CSS, images) for longer
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache other static files
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (uncomment and modify as needed)
# [context.production.environment]
#   REACT_APP_API_URL = "https://your-production-api.com"

# [context.deploy-preview.environment]
